services:
  - type: web
    name: laravel-app
    env: php
    plan: free
    region: oregon
    buildCommand: "composer install && php artisan key:generate"
    startCommand: "php artisan serve --host=0.0.0.0 --port=10000"
